[package]
name = "halo2aggregator-s"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2b_simd = "1"
halo2_proofs = { git = "https://github.com/junyu0312/halo2.git", branch = "gpu", default-features = true }
halo2ecc-s = { git = "https://github.com/lanbones/halo2ecc-s.git", branch = "0.1.0" }
ark-std = { version = "0.3", features = ["print-trace"] }
poseidon = { git = "https://github.com/lanbones/poseidon" }
num-integer = "0.1"
num-bigint = { version = "0.4", features = ["rand"] }
tera = "1.15.0"
sha2 = "0.10.6"

[features]
default = []
cuda = ["halo2_proofs/cuda", "halo2ecc-s/cuda"]