[package]
name = "halo2aggregator-s"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2_proofs = { git = "https://github.com/junyu0312/halo2.git", branch = "gpu", default-features = true, features = ["cuda"] }
ark-std = { version = "0.3", features = ["print-trace"] }

[features]
default = []
